"""Create table.

Revision ID: c4fe3af8ede5
Revises: 
Create Date: 2024-04-10 18:03:26.834434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fe3af8ede5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_status')
    op.drop_table('timezone_info')
    op.drop_table('business_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), nullable=True),
    sa.Column('open_time', sa.TIME(), nullable=True),
    sa.Column('close_time', sa.TIME(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timezone_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('store_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('store_status', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_name')
    )
    # ### end Alembic commands ###
